mysite/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_view.as_view(), name="login"),
    path('logout/', views.logout_view.as_view(), name="logout"),
    path('profile/', views.profile_view.as_view(), name="profile"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('add/', views.PollCreateView.as_view(), name='add'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote_view, name='vote'),
]

mysite/polls/models.py
import datetime

from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=400)
    thumbs_up = models.IntegerField(default=0)
    thumps_down = models.IntegerField(default=0)

    def __str__(self):
        return self.comment_text

    def get_absolute_url(self):
        return reverse('polls:results', kwargs={'pk': self.question.pk})


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

    class Meta:
        ordering = ['-votes']

mysite/polls/forms.py
from django import forms
from .models import Question, Choice, Comment
from django.utils.translation import gettext_lazy as _

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment_text']
		labels = {
            'comment_text': _('Comment'),
        }

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import messages
from django.views.generic import (
        ListView, 
        DetailView, 
        CreateView, 
        FormView
        )
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Question, Choice, Comment
from .forms import QuestionForm, ChoiceForm, CommentForm


class IndexView(ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:10]


# @method_decorator(login_required, name='dispatch')
class DetailView(DetailView):
    model = Question


class ResultsView(DetailView):
    model = Question
    template_name = 'polls/results.html'
    form_class = CommentForm


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a CommentForm
        form = self.form_class()
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST, instance=Comment())
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.question = Question.objects.get(id=kwargs['pk'])
            comment.author = request.user
            comment.save()
            messages.success(request, f'Comment Added!')
            return redirect('polls:results', kwargs['pk'])
        return render(request, self.template_name)


@method_decorator(login_required, name='dispatch')
class PollCreateView(CreateView):
    template_name = 'polls/question_form.html'
    number_of_choices = 3

    def get(self, request, *args, **kwargs):
        q_form = QuestionForm(instance=Question())
        c_forms = [ChoiceForm(prefix=str(x), instance=Choice()) for x in range(self.number_of_choices)]
        return render(request, self.template_name, {'q_form': q_form, 'c_forms': c_forms})

    def post(self, request):
        q_form = QuestionForm(request.POST, instance=Question())
        c_forms = [ChoiceForm(request.POST, prefix=str(x), instance=Choice()) for x in range(self.number_of_choices)]
        if q_form.is_valid() and all([cf.is_valid() for cf in c_forms]):
            question = q_form.save(commit=False)
            question.author = request.user
            question.save()
            for choice_form in c_forms:
                choice = choice_form.save(commit=False)
                choice.question = question
                choice.author = request.user
                choice.save()

            messages.success(request, f'Poll Added!')
            return redirect('polls:detail', question.pk)
        return render(request, self.template_name, {'q_form': q_form, 'c_forms': c_forms})


def vote_view(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/question_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/styles.css' %}" type="text/css">
    {% if title %}
    <title>Polls - {{ title }}</title>
    {% else %}
    <title>Polls</title>
    {% endif %}

  </head>
  <body>
    <header class="mb-4">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'polls:home' %}"><span class="navbar-brand mb-0 h1">Polls</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'polls:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'polls:home' %}">About</a>
            </div>
            <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'polls:add' %}">New Poll</a>
              <a class="nav-item nav-link" href="{% url 'accounts:profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
            {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-sm-3">
            <aside class="bg-light mt-4">
              <section><a class="nav-item nav-link" href="{% url 'accounts:profile' %}">My Profile</a></section>
              <section><a class="nav-item nav-link" href="{% url 'polls:add' %}">Create New Poll</a></section>
            </aside>
        </div>
      </div>
    </div> <!-- end container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row mt-4">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-primary">
                    {{ question.question_text }}
                </h5>
            </div>
            <div class="card-body">
                <div class="card-text">
                    <form action="{% url 'polls:vote' question.id %}" method="post">
                        {% csrf_token %}
                        {% for choice in question.choice_set.all %}
                            <div class="form-check mb-3">
                              <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                              <label class="form-check-label" for="choice{{ forloop.counter }}">
                                {{ choice.choice_text }}
                              </label>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Vote</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer">
              <a href="{% url 'polls:results' question.id %}">View Results</a>
            </div>
        </div>
    </div> <!-- end col -->
</div><!-- end row -->
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}
<h1 class="text-center">The Polling Station</h1>
{% if latest_question_list %}
    <div class="row mb-2">
        {% for question in latest_question_list %}
            <div class="col-sm-6 mb-3">
                <div class="card" style="min-height: 350px">
                    <div class="card-header">
                        <h5 class="card-title text-primary text-center mb-0">
                            <a href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a>
                        </h5>
                    </div>
                    <div class="card-body pt-0">
                    <div class="border-bottom py-1">
                        <div>
                          <img class="img-fluid rounded-circle" style="max-width:25%; height=auto" src="{{ question.author.profile.image.url }}">
                        </div>
                        <small class="text-muted">
                            Asked by <strong>{{ question.author }}</strong> on {{ question.pub_date }}
                        </small>
                    </div>

                    <div class="card-text">
                        <ul>
                            {% for choice in question.choice_set.all %}
                            <li><strong>{{ choice.choice_text }}</strong>: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                  </div>

                  <div class="card-footer text-center">
                      {% if user.is_authenticated %}
                      <a href="{% url 'polls:detail' question.id %}" 
                            class="btn btn-success btn-lg btn-block">Vote</a>
                      {% else %}
                      <a href="{% url 'accounts:register' %}" 
                            class="text-primary">Register to Vote</a>
                      {% endif %}
                  </div>
                </div>
            </div> <! -- end col -->
        {% if forloop.counter|divisibleby:"2" %}
        </div>
        <div class="row mb-2">
        {% endif %}
        {% endfor %}
    </div> <! -- end row -->
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock content%}

mysite/polls/templates/polls/poll_form.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row mt-4">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-primary text-center">
                    Create a new Poll
                </h5>
            </div>
            <div class="card-body">
                <div class="card-text">
                    <form action="{% url 'polls:add' %}" method="post">
                        {% csrf_token %}
                        {{ q_form|crispy }}
                        {% for choice_form in c_forms %}
                            {{ choice_form|crispy }}
                        {% endfor %}
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Create Poll</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer">
              <a href="{% url 'polls:home'%}">View Polls</a>
            </div>
        </div>
    </div> <!-- end col -->
</div><!-- end row -->
{% endblock %}

mysite/polls/templates/polls/question_detail.html
{% extends 'polls/base.html' %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row mt-4">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-primary">
                    {{ question.question_text }}
                </h5>
            </div>
            <div class="card-body">
                <div class="card-text">
                    <form action="{% url 'polls:vote' question.id %}" method="post">
                        {% csrf_token %}
                        {% for choice in question.choice_set.all %}
                            <div class="form-check mb-3">
                              <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                              <label class="form-check-label" for="choice{{ forloop.counter }}">
                                {{ choice.choice_text }}
                              </label>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Vote</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer">
              <a href="{% url 'polls:results' question.id %}">View Results</a>
            </div>
        </div>
    </div> <!-- end col -->
</div><!-- end row -->
{% endblock %}

mysite/polls/templates/polls/question_form.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row mt-4">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-primary text-center">
                    Create a new Poll
                </h5>
            </div>
            <div class="card-body">
                <div class="card-text">
                    <form action="{% url 'polls:add' %}" method="post">
                        {% csrf_token %}
                        {{ q_form|crispy }}
                        {% for choice_form in c_forms %}
                            {{ choice_form|crispy }}
                        {% endfor %}
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Create Poll</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer">
              <a href="{% url 'polls:home'%}">View Polls</a>
            </div>
        </div>
    </div> <!-- end col -->
</div><!-- end row -->
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mt-4">
    <div class="col-md-10 offset-md-1">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-primary mb-0">
                    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </h5>
                <small class="text-muted">
                    Asked by <strong>{{ question.author }}</strong> on {{ question.pub_date }}
                </small>
            </div>
            <div class="card-body">
                <div class="card-text border-bottom">
                    <ul>
                        {% for choice in question.choice_set.all %}
                            <li><strong>{{ choice.choice_text }}</strong>: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-text border-top pt-2">
                        {% for comment in question.comment_set.all %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="bg-light rounded">
                                    <img class="img-fluid rounded-circle d-inline" style="max-width:10%; height=auto" src="{{ comment.author.profile.image.url }}">
                                    <div class="text-muted d-inline">
                                        <strong>{{ comment.author }}</strong>:
                                        <p>{{ comment.comment_text }}</p>
                                    </div>    
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                </div>
                <div class="card-text border-top">
                {% if user.is_authenticated %}
                    <form method="POST" action="{% url 'polls:results' question.pk %}">
                        {% csrf_token %}
                        
                        <div class="form-group">
                        <!-- {{ form|crispy }} -->
                            <label for="{{ form.comment_text.id_for_label }}">Leave a Comment:</label>
                            {{ form.comment_text.errors }}
                            {{ form.comment_text }}
                        </div>
                        
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Post Comment</button>
                        </div>
                    </form>
                {% else %}
                <div class="text-muted text-center">
                    <a href="{% url 'accounts:register' %}">Register to leave a comment!</a>
                </div>
                {% endif %}
                </div>
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'polls:detail' question.id %}">Vote</a>
            </div>
        </div>
    </div> <!-- end col -->
</div><!-- end row -->
{% endblock %}